### ISSUE TITLE
ripemd160 error

### ISSUE THREAD

**Issue by as9ardth0r** [GitGab19/blockchain-address-list-generation#2]
Traceback (most recent call last):
  File "CompBitcoinGen.py", line 44, in <module>
    pub = AddressGeneration.BitcoinClassicAddressComputation(public_key[0])
  File "..\AddressGeneration.py", line 126, in BitcoinClassicAddressComputation
    ripemd160 = hashlib.new('Ripemd160')
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\hashlib.py", line 155, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type Ripemd160

**Comment by GitGab19** [comment]
Do you have it in your local SSL library?
You can check with: `openssl list-message-digest-algorithms` in your terminal.

**Comment by GitGab19** [comment]
> Traceback (most recent call last): File "CompBitcoinGen.py", line 44, in pub = AddressGeneration.BitcoinClassicAddressComputation(public_key[0]) File "..\AddressGeneration.py", line 126, in BitcoinClassicAddressComputation ripemd160 = hashlib.new('Ripemd160') File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\hashlib.py", line 155, in __hash_new return __get_builtin_constructor(name)(data) File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\hashlib.py", line 113, in __get_builtin_constructor raise ValueError('unsupported hash type ' + name) ValueError: unsupported hash type Ripemd160

Do you have it in your local SSL library?
You can check with: openssl list-message-digest-algorithms in your terminal.
